server:
  port: ${PORT:9002}
  servlet:
    context-path: /review-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb+srv://admin:phambaophuc@mydb.t3eg6sl.mongodb.net/fast_food_express_db
  config:
    import: 'optional:configserver:'
#  profiles:
#    active: dev
#  cloud:
#    config:
#      profile: dev

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  tracing:
    sampling:
      probability: 1.0

springdoc:
  version: '2.3.0'
  api-docs:
    version: openapi_3_1
  cache:
    disabled: true

gateway:
  url: ${GATEWAY_URL:http://localhost:8765}
